export const TRADE_LOCATION_META = {
  plumbers: {
    tradeName: 'Plumbers',
    tradeSlug: 'plumbers',
    metaTitle: 'Web Design for Plumbers in Bath | From £399 | SEO Kings',
    metaDescription: 'Websites for plumbers in Bath that rank on Google. Gas Safe badge, emergency page, dedicated service pages. Local SEO for Bath plumbers from £399.',
    headline: 'Web Design for Plumbers in Bath',
    intro: 'Bath has thousands of period properties — Georgian terraces, Victorian conversions, listed buildings — all with complex plumbing. When someone in Bath searches "plumber Bath" or "emergency plumber Bath", they need someone local and qualified. Your website has to show that you understand Bath properties and Bath plumbing issues. We build plumber websites that do exactly that.',
    bathSpecifics: [
      'Listed building plumbing expertise — Bath has more Grade I and II listed homes than almost anywhere in the UK',
      'Hard water area — Bath sits on limestone, so scale and limescale problems are constant. Show you know the area',
      'Georgian and Victorian pipe systems — older Bath properties need plumbers who understand traditional pipework',
      'Emergency plumber in Bath — high search volume from students and residents in the city centre',
      'Conservation area restrictions — some Bath plumbing works need listed building consent',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Do I need a separate website page for Bath plumbing?', a: 'Yes. "Plumber Bath" is one of the highest-volume local searches in Somerset. A dedicated Bath page lets you mention Bath-area specifics — listed buildings, hard water, conservation areas — that generic pages miss. It also helps you rank for "plumber BA1" and Bath postcode searches.' },
      { q: 'Should my Bath page mention listed buildings?', a: 'Absolutely. Bath has over 6,000 listed buildings. Homeowners in conservation areas specifically search for plumbers who understand listed property work. Mentioning it on your Bath page targets those high-value jobs.' },
      { q: 'How long until my Bath plumber website ranks?', a: 'Google Business Profile optimisation can get you into the Bath map pack within weeks. Website rankings for "plumber Bath" typically take 3–6 months of consistent SEO. We start with quick wins and build from there.' },
      { q: 'Can you write the Bath-specific content for me?', a: 'Yes. We write all website copy as part of the build. We research Bath-specific plumbing issues, local landmarks and search terms so your Bath page sounds genuine and ranks well.' },
    ],
  },
  electricians: {
    tradeName: 'Electricians',
    tradeSlug: 'electricians',
    metaTitle: 'Web Design for Electricians in Bath | From £399 | SEO Kings',
    metaDescription: 'Websites for electricians in Bath that rank on Google. NICEIC/Part P badges, service pages, area coverage. Local SEO for Bath electricians from £399.',
    headline: 'Web Design for Electricians in Bath',
    intro: 'Bath\'s housing stock ranges from Georgian townhouses to modern developments — and the electrical needs are just as varied. Period properties need rewiring and consumer unit upgrades. New builds need full installations. When someone searches "electrician Bath", they want someone who knows the local building stock. We build electrician websites that prove you do.',
    bathSpecifics: [
      'Period property rewiring — Bath\'s Georgian and Victorian homes often need full rewire work',
      'Consumer unit upgrades — older Bath properties frequently need modern fuse box replacements',
      'Conservation area electrical work — routing cables in listed buildings requires care and experience',
      'New build electrical installations — Bath has ongoing developments on the edges of the city',
      'Student HMO electrical safety — Bath has a large student rental market needing regular safety checks',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Should my website mention Bath-specific electrical work?', a: 'Yes. Period property rewiring is a major Bath search term. Buyers and landlords in Bath conservation areas specifically look for electricians who understand listed building electrics. Your Bath page should mention this work front and centre.' },
      { q: 'How do I rank for "electrician Bath" on Google?', a: 'Start with your Google Business Profile — optimise it for Bath and the BA1/BA2 postcodes. Then your website needs a Bath page with local content, Bath service areas, and consistent citations across local directories. We handle all of this.' },
      { q: 'Do students and landlords search for electricians in Bath?', a: 'Yes — Bath has two universities and a large HMO rental market. Landlords need EICRs and safety certs regularly. A page targeting "landlord electrical safety Bath" can bring consistent annual work.' },
      { q: 'What Bath areas should I list on my website?', a: 'At minimum: Bath city centre, Widcombe, Larkhall, Lansdown, Weston and Combe Down. These are the main residential areas with the highest search volume for electricians.' },
    ],
  },
  roofers: {
    tradeName: 'Roofers',
    tradeSlug: 'roofers',
    metaTitle: 'Web Design for Roofers in Bath | From £399 | SEO Kings',
    metaDescription: 'Websites for roofers in Bath that rank on Google. Before/after gallery, emergency page, insurance work. Local SEO for Bath roofers from £399.',
    headline: 'Web Design for Roofers in Bath',
    intro: 'Bath\'s rooftops define the city — from Georgian slate to Victorian clay tile to modern flat roofs on extensions. Roofing work in Bath means understanding period properties, conservation area restrictions, and heritage materials. When someone searches "roofer Bath", they need a specialist, not a general builder. We build roofer websites that show you are one.',
    bathSpecifics: [
      'Heritage roofing expertise — Bath has more listed roofs than most cities in England',
      'Slate and clay tile specialists — the dominant roofing materials across Bath\'s older housing stock',
      'Leadwork and flashings — Georgian parapets and valley gutters need traditional lead skills',
      'Flat roof extensions — modern Bath extensions often use EPDM and fibreglass flat roofing',
      'Storm damage and insurance work — winter storms regularly bring emergency roofing calls in Bath',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Why do I need a Bath-specific roofing page?', a: '"Roofer Bath" gets significant search volume, and the people searching want someone who understands Bath\'s period properties. A generic roofing page can\'t mention heritage slate, leadwork, or conservation area restrictions — but a Bath page can, and that\'s what converts those searches into calls.' },
      { q: 'Should I show before and after photos of Bath roofing jobs?', a: 'Absolutely. Roofing is visual — homeowners want to see the quality of your work. Before/after photos of Bath properties are especially powerful because they show you work on homes like theirs. We build photo galleries into every roofer website.' },
      { q: 'Do insurance roofing jobs in Bath need a separate page?', a: 'Yes if you do insurance work. "Storm damage roofer Bath" and "insurance roofer Bath" are searched after every major storm. A dedicated page means you capture that demand when it spikes.' },
      { q: 'What Bath postcodes should I target?', a: 'BA1 and BA2 cover the whole city. Focus your Bath page on BA1 (city centre, Lansdown, Weston) and BA2 (Widcombe, Combe Down, Odd Down) as the primary service areas.' },
    ],
  },
  builders: {
    tradeName: 'Builders',
    tradeSlug: 'builders',
    metaTitle: 'Web Design for Builders in Bath | From £399 | SEO Kings',
    metaDescription: 'Websites for builders in Bath that rank on Google. Project galleries, service pages, planning expertise. Local SEO for Bath builders from £399.',
    headline: 'Web Design for Builders in Bath',
    intro: 'Building in Bath is different. Conservation area rules, listed building consent, Bath stone matching, planning permission quagmires — Bath homeowners need a builder who understands all of it before they pick up the phone. We build websites that show you do, so when they search "builder Bath", they call you.',
    bathSpecifics: [
      'Conservation area expertise — most of central Bath is covered by conservation area restrictions',
      'Listed building consent experience — Bath has Grade I, Grade II* and Grade II listed properties throughout',
      'Bath stone matching — extensions and renovations must match the local limestone, and planners enforce this',
      'Planning permission success — Bath & North East Somerset planning department is known for being strict',
      'Period property extensions — rear extensions on Georgian terraces and Victorian villas are a major Bath builder specialism',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Why do Bath builders need a specialist website?', a: 'Bath is one of the most regulated building environments in the UK. Conservation areas, listed buildings, Article 4 directions, Article 4(2) restrictions — homeowners search specifically for builders who understand Bath planning. A generic builder website can\'t communicate that. A Bath-specific page does.' },
      { q: 'Should my Bath page mention planning permission?', a: 'Yes. "Builder Bath planning permission" is a real search query. Bath homeowners worry about planning before they worry about the build. If your website shows you handle planning applications in Bath, you\'ll get more enquiries.' },
      { q: 'How do I rank for "builder Bath" on Google?', a: 'Start with Google Business Profile optimisation for Bath and the BA1/BA2 postcodes. Then your website needs Bath-specific content, project galleries of local work, and consistent citations. We set all of this up.' },
      { q: 'Can you help with Bath-specific copywriting?', a: 'Yes. We write builder website copy that mentions Bath planning, Bath stone, conservation areas, and local knowledge. It reads naturally because we understand the local building landscape.' },
    ],
  },
  landscapers: {
    tradeName: 'Landscapers',
    tradeSlug: 'landscapers',
    metaTitle: 'Web Design for Landscapers in Bath | From £399 | SEO Kings',
    metaDescription: 'Websites for landscapers in Bath that rank on Google. Before/after gallery, garden design pages, area coverage. Local SEO for Bath landscapers from £399.',
    headline: 'Web Design for Landscapers in Bath',
    intro: 'Bath gardens are like no other — steep hillsides, walled Georgian courtyards, lime-rich soil, and views that homeowners want to make the most of. When someone searches "landscaper Bath" or "garden design Bath", they want a local expert who understands the terrain. We build landscaper websites that prove you are one.',
    bathSpecifics: [
      'Steep sloping gardens — Bath\'s hills create some of the most challenging landscaping in Somerset',
      'Period garden design — Georgian and Victorian gardens with formal layouts, stone walls, and heritage planting',
      'Limestone walls and terracing — Bath stone retaining walls are a specialist landscaping skill',
      'Small inner-city courtyards — Bath city centre homes often have tiny courtyard gardens needing clever design',
      'Views and planting — hillside Bath gardens have panoramic views that garden design should frame and enhance',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Do I need a separate page for Bath landscaping?', a: 'Yes. "Landscaper Bath" and "garden design Bath" are high-volume searches with commercial intent. A Bath page lets you mention Bath stone, steep gardens, and conservation area restrictions — things that differentiate you from generic landscapers.' },
      { q: 'Should I show photos of Bath garden projects?', a: 'Absolutely. Landscaping is one of the most visual trades. Before/after photos of Bath gardens — especially steep hillside transformations — are incredibly persuasive. We build photo galleries into every landscaper website.' },
      { q: 'Do conservation areas affect Bath landscaping?', a: 'Yes. Some Bath conservation areas restrict fence heights, tree removal, and hard landscaping. Homeowners know this and search for landscapers who understand the rules. Your Bath page should mention it.' },
      { q: 'What Bath areas should I list?', a: 'Bath city centre, Widcombe, Larkhall, Lansdown, Weston and Combe Down at minimum. These have the highest concentration of homeowners spending on garden projects.' },
    ],
  },
  cleaners: {
    tradeName: 'Cleaning Services',
    tradeSlug: 'cleaners',
    metaTitle: 'Web Design for Cleaning Services in Bath | From £399 | SEO Kings',
    metaDescription: 'Websites for cleaners in Bath that rank on Google. Service pages, area coverage, review integration. Local SEO for Bath cleaning businesses from £399.',
    headline: 'Web Design for Cleaning Services in Bath',
    intro: 'Bath has a huge cleaning market — student rentals, holiday lets, professional households, and commercial premises across the city centre. But most Bath cleaning businesses have no website or a poor one. When someone searches "cleaner Bath", a professional, fast, mobile-friendly website is often enough to win the job.',
    bathSpecifics: [
      'Student let cleaning — Bath\'s two universities create huge demand for end-of-tenancy cleaning',
      'Holiday let turnover — Bath\'s tourist industry means Airbnb and holiday let cleans are constant',
      'Period property care — cleaning Georgian properties needs care with period features and Bath stone',
      'Commercial cleaning — Bath city centre offices, restaurants, and shops need regular cleaning',
      'Hard water area — limescale is a constant issue in Bath, so deep cleaning and descaling are high-demand services',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Do Bath cleaners really need a website?', a: 'Yes. Most Bath cleaners rely on word of mouth alone, but Google searches for "cleaner Bath" happen every day. A professional website with reviews, services and a clear contact form wins those searches. Your competitors who don\'t have one lose out.' },
      { q: 'Should I mention student and holiday let cleaning?', a: 'Absolutely. End-of-tenancy and Airbnb cleaning is a major Bath market. Landlords and hosts search specifically for "end of tenancy cleaning Bath" and "Airbnb cleaning Bath". Dedicated service pages for these target those exact searches.' },
      { q: 'How do reviews help my Bath cleaning website?', a: 'Massively. Cleaning is a trust-based service — homeowners are letting you into their home. A website with Google reviews integrated prominently converts far better than one without. We build review display into every cleaning website.' },
      { q: 'Can I target specific Bath postcodes?', a: 'Yes. BA1 and BA2 cover all of Bath. We build area pages and Google Business Profile optimisation so you rank for "cleaner BA1", "cleaner BA2" and Bath neighbourhood searches.' },
    ],
  },
  'painters-decorators': {
    tradeName: 'Painters & Decorators',
    tradeSlug: 'painters-decorators',
    metaTitle: 'Web Design for Painters & Decorators in Bath | From £399 | SEO Kings',
    metaDescription: 'Websites for painters and decorators in Bath that rank on Google. Heritage painting, period properties, service pages. Local SEO for Bath decorators from £399.',
    headline: 'Web Design for Painters & Decorators in Bath',
    intro: 'More period properties per square mile than almost anywhere in the UK. Bath decorators work on Georgian townhouses, Victorian villas, listed interiors, and modern homes — and each needs a different approach. When someone searches "painter decorator Bath", they want someone who gets Bath. We build decorator websites that show you do.',
    bathSpecifics: [
      'Heritage painting expertise — Bath\'s listed interiors need traditional lime wash, distemper and period-correct finishes',
      'Cornice and ceiling rose restoration — decorative plaster painting is a specialist Bath decorator skill',
      'Conservation area restrictions — exterior painting in Bath conservation areas may need planning consent for colour changes',
      'Sash window painting — Bath has thousands of sash windows that need specialist painting and draught-proofing',
      'Farrow & Ball and heritage colour ranges — Bath homeowners expect decorators who understand period colour palettes',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Why do Bath painters need a specialist website?', a: '"Painter decorator Bath" is a competitive search. Bath homeowners want decorators who understand heritage properties, period colour palettes, and conservation restrictions. A generic decorator website doesn\'t mention these. A Bath page does — and it converts those searches into calls.' },
      { q: 'Should my website mention heritage and period property work?', a: 'Yes. Heritage painting is a major differentiator in Bath. Homeowners in Bath conservation areas specifically search for decorators with period property experience. This should be prominent on your Bath page.' },
      { q: 'Do I need before and after photos on my Bath page?', a: 'Absolutely. Before/after photos of Bath period properties — sash windows, cornices, heritage colour transformations — are the most persuasive content on a decorator website. We build galleries into every site.' },
      { q: 'Can you write Bath-specific decorating content?', a: 'Yes. We write copy that mentions Bath stone, Farrow & Ball, cornice restoration, sash window painting and conservation area rules. It sounds genuine because we understand the Bath decorating landscape.' },
    ],
  },
};