export const TRADE_LOCATION_META = {
  plumbers: {
    tradeName: 'Plumbers',
    tradeSlug: 'plumbers',
    metaTitle: 'Web Design for Plumbers in Bath | From £250 | SEO Kings',
    metaDescription: 'Websites for plumbers in Bath that rank on Google. Gas Safe badge, emergency page, dedicated service pages. Local SEO for Bath plumbers from £250.',
    headline: 'Web Design for Plumbers in Bath',
    intro: 'Bath has thousands of period properties — Georgian terraces, Victorian conversions, listed buildings — all with complex plumbing. When someone in Bath searches "plumber Bath" or "emergency plumber Bath", they need someone local and qualified. Your website has to show that you understand Bath properties and Bath plumbing issues. We build plumber websites that do exactly that.',
    bathSpecifics: [
      'Listed building plumbing expertise — Bath has more Grade I and II listed homes than almost anywhere in the UK',
      'Hard water area — Bath sits on limestone, so scale and limescale problems are constant. Show you know the area',
      'Georgian and Victorian pipe systems — older Bath properties need plumbers who understand traditional pipework',
      'Emergency plumber in Bath — high search volume from students and residents in the city centre',
      'Conservation area restrictions — some Bath plumbing works need listed building consent',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Do I need a separate website page for Bath plumbing?', a: 'Yes. "Plumber Bath" is one of the highest-volume local searches in Somerset. A dedicated Bath page lets you mention Bath-area specifics — listed buildings, hard water, conservation areas — that generic pages miss. It also helps you rank for "plumber BA1" and Bath postcode searches.' },
      { q: 'Should my Bath page mention listed buildings?', a: 'Absolutely. Bath has over 6,000 listed buildings. Homeowners in conservation areas specifically search for plumbers who understand listed property work. Mentioning it on your Bath page targets those high-value jobs.' },
      { q: 'How long until my Bath plumber website ranks?', a: 'Google Business Profile optimisation can get you into the Bath map pack within weeks. Website rankings for "plumber Bath" typically take 3–6 months of consistent SEO. We start with quick wins and build from there.' },
      { q: 'Can you write the Bath-specific content for me?', a: 'Yes. We write all website copy as part of the build. We research Bath-specific plumbing issues, local landmarks and search terms so your Bath page sounds genuine and ranks well.' },
    ],
  },
  electricians: {
    tradeName: 'Electricians',
    tradeSlug: 'electricians',
    metaTitle: 'Web Design for Electricians in Bath | From £250 | SEO Kings',
    metaDescription: 'Websites for electricians in Bath that rank on Google. NICEIC/Part P badges, service pages, area coverage. Local SEO for Bath electricians from £250.',
    headline: 'Web Design for Electricians in Bath',
    intro: 'Bath\'s housing stock ranges from Georgian townhouses to modern developments — and the electrical needs are just as varied. Period properties need rewiring and consumer unit upgrades. New builds need full installations. When someone searches "electrician Bath", they want someone who knows the local building stock. We build electrician websites that prove you do.',
    bathSpecifics: [
      'Period property rewiring — Bath\'s Georgian and Victorian homes often need full rewire work',
      'Consumer unit upgrades — older Bath properties frequently need modern fuse box replacements',
      'Conservation area electrical work — routing cables in listed buildings requires care and experience',
      'New build electrical installations — Bath has ongoing developments on the edges of the city',
      'Student HMO electrical safety — Bath has a large student rental market needing regular safety checks',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Should my website mention Bath-specific electrical work?', a: 'Yes. Period property rewiring is a major Bath search term. Buyers and landlords in Bath conservation areas specifically look for electricians who understand listed building electrics. Your Bath page should mention this work front and centre.' },
      { q: 'How do I rank for "electrician Bath" on Google?', a: 'Start with your Google Business Profile — optimise it for Bath and the BA1/BA2 postcodes. Then your website needs a Bath page with local content, Bath service areas, and consistent citations across local directories. We handle all of this.' },
      { q: 'Do students and landlords search for electricians in Bath?', a: 'Yes — Bath has two universities and a large HMO rental market. Landlords need EICRs and safety certs regularly. A page targeting "landlord electrical safety Bath" can bring consistent annual work.' },
      { q: 'What Bath areas should I list on my website?', a: 'At minimum: Bath city centre, Widcombe, Larkhall, Lansdown, Weston and Combe Down. These are the main residential areas with the highest search volume for electricians.' },
    ],
  },
  roofers: {
    tradeName: 'Roofers',
    tradeSlug: 'roofers',
    metaTitle: 'Web Design for Roofers in Bath | From £250 | SEO Kings',
    metaDescription: 'Websites for roofers in Bath that rank on Google. Before/after gallery, emergency page, insurance work. Local SEO for Bath roofers from £250.',
    headline: 'Web Design for Roofers in Bath',
    intro: 'Bath\'s rooftops define the city — from Georgian slate to Victorian clay tile to modern flat roofs on extensions. Roofing work in Bath means understanding period properties, conservation area restrictions, and heritage materials. When someone searches "roofer Bath", they need a specialist, not a general builder. We build roofer websites that show you are one.',
    bathSpecifics: [
      'Heritage roofing expertise — Bath has more listed roofs than most cities in England',
      'Slate and clay tile specialists — the dominant roofing materials across Bath\'s older housing stock',
      'Leadwork and flashings — Georgian parapets and valley gutters need traditional lead skills',
      'Flat roof extensions — modern Bath extensions often use EPDM and fibreglass flat roofing',
      'Storm damage and insurance work — winter storms regularly bring emergency roofing calls in Bath',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Why do I need a Bath-specific roofing page?', a: '"Roofer Bath" gets significant search volume, and the people searching want someone who understands Bath\'s period properties. A generic roofing page can\'t mention heritage slate, leadwork, or conservation area restrictions — but a Bath page can, and that\'s what converts those searches into calls.' },
      { q: 'Should I show before and after photos of Bath roofing jobs?', a: 'Absolutely. Roofing is visual — homeowners want to see the quality of your work. Before/after photos of Bath properties are especially powerful because they show you work on homes like theirs. We build photo galleries into every roofer website.' },
      { q: 'Do insurance roofing jobs in Bath need a separate page?', a: 'Yes if you do insurance work. "Storm damage roofer Bath" and "insurance roofer Bath" are searched after every major storm. A dedicated page means you capture that demand when it spikes.' },
      { q: 'What Bath postcodes should I target?', a: 'BA1 and BA2 cover the whole city. Focus your Bath page on BA1 (city centre, Lansdown, Weston) and BA2 (Widcombe, Combe Down, Odd Down) as the primary service areas.' },
    ],
  },
  builders: {
    tradeName: 'Builders',
    tradeSlug: 'builders',
    metaTitle: 'Web Design for Builders in Bath | From £250 | SEO Kings',
    metaDescription: 'Websites for builders in Bath that rank on Google. Project galleries, service pages, planning expertise. Local SEO for Bath builders from £250.',
    headline: 'Web Design for Builders in Bath',
    intro: 'Building in Bath is different. Conservation area rules, listed building consent, Bath stone matching, planning permission quagmires — Bath homeowners need a builder who understands all of it before they pick up the phone. We build websites that show you do, so when they search "builder Bath", they call you.',
    bathSpecifics: [
      'Conservation area expertise — most of central Bath is covered by conservation area restrictions',
      'Listed building consent experience — Bath has Grade I, Grade II* and Grade II listed properties throughout',
      'Bath stone matching — extensions and renovations must match the local limestone, and planners enforce this',
      'Planning permission success — Bath & North East Somerset planning department is known for being strict',
      'Period property extensions — rear extensions on Georgian terraces and Victorian villas are a major Bath builder specialism',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Why do Bath builders need a specialist website?', a: 'Bath is one of the most regulated building environments in the UK. Conservation areas, listed buildings, Article 4 directions, Article 4(2) restrictions — homeowners search specifically for builders who understand Bath planning. A generic builder website can\'t communicate that. A Bath-specific page does.' },
      { q: 'Should my Bath page mention planning permission?', a: 'Yes. "Builder Bath planning permission" is a real search query. Bath homeowners worry about planning before they worry about the build. If your website shows you handle planning applications in Bath, you\'ll get more enquiries.' },
      { q: 'How do I rank for "builder Bath" on Google?', a: 'Start with Google Business Profile optimisation for Bath and the BA1/BA2 postcodes. Then your website needs Bath-specific content, project galleries of local work, and consistent citations. We set all of this up.' },
      { q: 'Can you help with Bath-specific copywriting?', a: 'Yes. We write builder website copy that mentions Bath planning, Bath stone, conservation areas, and local knowledge. It reads naturally because we understand the local building landscape.' },
    ],
  },
  landscapers: {
    tradeName: 'Landscapers',
    tradeSlug: 'landscapers',
    metaTitle: 'Web Design for Landscapers in Bath | From £250 | SEO Kings',
    metaDescription: 'Websites for landscapers in Bath that rank on Google. Before/after gallery, garden design pages, area coverage. Local SEO for Bath landscapers from £250.',
    headline: 'Web Design for Landscapers in Bath',
    intro: 'Bath gardens are like no other — steep hillsides, walled Georgian courtyards, lime-rich soil, and views that homeowners want to make the most of. When someone searches "landscaper Bath" or "garden design Bath", they want a local expert who understands the terrain. We build landscaper websites that prove you are one.',
    bathSpecifics: [
      'Steep sloping gardens — Bath\'s hills create some of the most challenging landscaping in Somerset',
      'Period garden design — Georgian and Victorian gardens with formal layouts, stone walls, and heritage planting',
      'Limestone walls and terracing — Bath stone retaining walls are a specialist landscaping skill',
      'Small inner-city courtyards — Bath city centre homes often have tiny courtyard gardens needing clever design',
      'Views and planting — hillside Bath gardens have panoramic views that garden design should frame and enhance',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Do I need a separate page for Bath landscaping?', a: 'Yes. "Landscaper Bath" and "garden design Bath" are high-volume searches with commercial intent. A Bath page lets you mention Bath stone, steep gardens, and conservation area restrictions — things that differentiate you from generic landscapers.' },
      { q: 'Should I show photos of Bath garden projects?', a: 'Absolutely. Landscaping is one of the most visual trades. Before/after photos of Bath gardens — especially steep hillside transformations — are incredibly persuasive. We build photo galleries into every landscaper website.' },
      { q: 'Do conservation areas affect Bath landscaping?', a: 'Yes. Some Bath conservation areas restrict fence heights, tree removal, and hard landscaping. Homeowners know this and search for landscapers who understand the rules. Your Bath page should mention it.' },
      { q: 'What Bath areas should I list?', a: 'Bath city centre, Widcombe, Larkhall, Lansdown, Weston and Combe Down at minimum. These have the highest concentration of homeowners spending on garden projects.' },
    ],
  },
  cleaners: {
    tradeName: 'Cleaning Services',
    tradeSlug: 'cleaners',
    metaTitle: 'Web Design for Cleaning Services in Bath | From £250 | SEO Kings',
    metaDescription: 'Websites for cleaners in Bath that rank on Google. Service pages, area coverage, review integration. Local SEO for Bath cleaning businesses from £250.',
    headline: 'Web Design for Cleaning Services in Bath',
    intro: 'Bath has a huge cleaning market — student rentals, holiday lets, professional households, and commercial premises across the city centre. But most Bath cleaning businesses have no website or a poor one. When someone searches "cleaner Bath", a professional, fast, mobile-friendly website is often enough to win the job.',
    bathSpecifics: [
      'Student let cleaning — Bath\'s two universities create huge demand for end-of-tenancy cleaning',
      'Holiday let turnover — Bath\'s tourist industry means Airbnb and holiday let cleans are constant',
      'Period property care — cleaning Georgian properties needs care with period features and Bath stone',
      'Commercial cleaning — Bath city centre offices, restaurants, and shops need regular cleaning',
      'Hard water area — limescale is a constant issue in Bath, so deep cleaning and descaling are high-demand services',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Do Bath cleaners really need a website?', a: 'Yes. Most Bath cleaners rely on word of mouth alone, but Google searches for "cleaner Bath" happen every day. A professional website with reviews, services and a clear contact form wins those searches. Your competitors who don\'t have one lose out.' },
      { q: 'Should I mention student and holiday let cleaning?', a: 'Absolutely. End-of-tenancy and Airbnb cleaning is a major Bath market. Landlords and hosts search specifically for "end of tenancy cleaning Bath" and "Airbnb cleaning Bath". Dedicated service pages for these target those exact searches.' },
      { q: 'How do reviews help my Bath cleaning website?', a: 'Massively. Cleaning is a trust-based service — homeowners are letting you into their home. A website with Google reviews integrated prominently converts far better than one without. We build review display into every cleaning website.' },
      { q: 'Can I target specific Bath postcodes?', a: 'Yes. BA1 and BA2 cover all of Bath. We build area pages and Google Business Profile optimisation so you rank for "cleaner BA1", "cleaner BA2" and Bath neighbourhood searches.' },
    ],
  },
  'painters-decorators': {
    tradeName: 'Painters & Decorators',
    tradeSlug: 'painters-decorators',
    metaTitle: 'Web Design for Painters & Decorators in Bath | From £250 | SEO Kings',
    metaDescription: 'Websites for painters and decorators in Bath that rank on Google. Heritage painting, period properties, service pages. Local SEO for Bath decorators from £250.',
    headline: 'Web Design for Painters & Decorators in Bath',
    intro: 'More period properties per square mile than almost anywhere in the UK. Bath decorators work on Georgian townhouses, Victorian villas, listed interiors, and modern homes — and each needs a different approach. When someone searches "painter decorator Bath", they want someone who gets Bath. We build decorator websites that show you do.',
    bathSpecifics: [
      'Heritage painting expertise — Bath\'s listed interiors need traditional lime wash, distemper and period-correct finishes',
      'Cornice and ceiling rose restoration — decorative plaster painting is a specialist Bath decorator skill',
      'Conservation area restrictions — exterior painting in Bath conservation areas may need planning consent for colour changes',
      'Sash window painting — Bath has thousands of sash windows that need specialist painting and draught-proofing',
      'Farrow & Ball and heritage colour ranges — Bath homeowners expect decorators who understand period colour palettes',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Why do Bath painters need a specialist website?', a: '"Painter decorator Bath" is a competitive search. Bath homeowners want decorators who understand heritage properties, period colour palettes, and conservation restrictions. A generic decorator website doesn\'t mention these. A Bath page does — and it converts those searches into calls.' },
      { q: 'Should my website mention heritage and period property work?', a: 'Yes. Heritage painting is a major differentiator in Bath. Homeowners in Bath conservation areas specifically search for decorators with period property experience. This should be prominent on your Bath page.' },
      { q: 'Do I need before and after photos on my Bath page?', a: 'Absolutely. Before/after photos of Bath period properties — sash windows, cornices, heritage colour transformations — are the most persuasive content on a decorator website. We build galleries into every site.' },
      { q: 'Can you write Bath-specific decorating content?', a: 'Yes. We write copy that mentions Bath stone, Farrow & Ball, cornice restoration, sash window painting and conservation area rules. It sounds genuine because we understand the Bath decorating landscape.' },
    ],
  },
  'kitchen-fitters': {
    tradeName: 'Kitchen Fitters',
    tradeSlug: 'kitchen-fitters',
    metaTitle: 'Web Design for Kitchen Fitters in Bath | From £250 | SEO Kings',
    metaDescription: 'Websites for kitchen fitters in Bath that rank on Google. Project galleries, service pages, area coverage. Local SEO for Bath kitchen fitters from £250.',
    headline: 'Web Design for Kitchen Fitters in Bath',
    intro: 'Bath homeowners spend big on kitchens — period property renovations, modern extensions, open-plan living. When they search "kitchen fitter Bath" or "kitchen design Bath", they want to see your work before they call. We build kitchen fitter websites that showcase your projects and convert searches into enquiries.',
    bathSpecifics: [
      'Period property kitchen renovations — working within Bath\'s listed building and conservation area restrictions',
      'Bath stone and traditional features — kitchens that complement Georgian and Victorian architecture',
      'Open-plan kitchen extensions — popular in Bath\'s Victorian terraces, often requiring structural work and planning permission',
      'High-end finishes — Bath homeowners expect premium appliances, worktops and fittings',
      'Small city-centre kitchens — Bath\'s Georgian townhouses often have compact kitchens needing clever design',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Why do kitchen fitters in Bath need a specialist website?', a: 'Kitchen fitting is a high-value, high-trust decision. Bath homeowners research carefully before choosing — and they search "kitchen fitter Bath" looking for someone local with a portfolio. A professional website with project galleries wins those searches.' },
      { q: 'Should I show before and after photos?', a: 'Absolutely. Kitchen transformations are one of the most visual home improvements. Before/after photos of Bath kitchens — especially period properties — are the single most persuasive thing on your website.' },
      { q: 'Do I need to mention listed buildings on my Bath page?', a: 'Yes. Bath has thousands of listed properties, and kitchen renovations in conservation areas often need listed building consent. Homeowners specifically search for kitchen fitters who understand Bath planning restrictions.' },
      { q: 'What Bath areas should I target?', a: 'Bath city centre, Widcombe, Larkhall, Lansdown, Weston and Combe Down at minimum. Bath postcode targeting for BA1 and BA2 covers the whole city.' },
    ],
  },
  'bathroom-fitters': {
    tradeName: 'Bathroom Fitters',
    tradeSlug: 'bathroom-fitters',
    metaTitle: 'Web Design for Bathroom Fitters in Bath | From £250 | SEO Kings',
    metaDescription: 'Websites for bathroom fitters in Bath that rank on Google. Project galleries, wet room pages, area coverage. Local SEO for Bath bathroom fitters from £250.',
    headline: 'Web Design for Bathroom Fitters in Bath',
    intro: 'Bathroom renovations are one of the biggest home investments in Bath — from Georgian ensuites to wet rooms in modern extensions. When someone searches "bathroom fitter Bath", they want to see proof you can deliver. We build websites that show your best work and turn searches into bookings.',
    bathSpecifics: [
      'Period property bathrooms — working with Bath\'s original features, pipework and room dimensions',
      'Small bathroom design — Bath\'s Georgian and Victorian properties often have compact bathrooms needing space-saving solutions',
      'Wet rooms and walk-in showers — increasingly popular in Bath extensions and loft conversions',
      'Underfloor heating — a common addition in Bath bathroom renovations, especially in stone-floored period properties',
      'Listed building restrictions — some Bath bathroom renovations need listed building consent for structural changes',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Do bathroom fitters in Bath need a dedicated website?', a: 'Yes. "Bathroom fitter Bath" is a high-volume, high-intent search. Homeowners want to see your portfolio, read reviews and check you work in their area. A website does all of this — word of mouth can\'t.' },
      { q: 'Should I mention period property bathroom work?', a: 'Absolutely. Bath is full of Georgian and Victorian homes with original bathrooms that need sensitive renovation. Homeowners specifically search for "bathroom fitter period property Bath" — your website should target this.' },
      { q: 'How important is a photo gallery for a bathroom fitting website?', a: 'Critical. Bathroom fitting is visual and trust-based. Homeowners will not call a bathroom fitter who doesn\'t show their work online. We build photo galleries into every bathroom fitter website.' },
      { q: 'Can I target specific Bath postcodes?', a: 'Yes. BA1 and BA2 cover all of Bath. We build area pages and optimise your Google Business Profile so you rank for "bathroom fitter BA1" and Bath neighbourhood searches.' },
    ],
  },
  'heating-engineers': {
    tradeName: 'Heating Engineers',
    tradeSlug: 'heating-engineers',
    metaTitle: 'Web Design for Heating Engineers in Bath | From £250 | SEO Kings',
    metaDescription: 'Websites for heating engineers in Bath that rank on Google. Gas Safe badge, emergency page, boiler service pages. Local SEO for Bath heating engineers from £250.',
    headline: 'Web Design for Heating Engineers in Bath',
    intro: 'When a boiler breaks in Bath, it\'s an emergency. "Heating engineer Bath", "boiler repair Bath", "emergency gas engineer" — these are urgent, high-intent searches from people who need you now. We build heating engineer websites that show your Gas Safe credentials, your emergency response, and your local knowledge.',
    bathSpecifics: [
      'Gas Safe registration — the first thing Bath homeowners check when searching for a heating engineer',
      'Emergency boiler repair — Bath\'s period properties have older boilers that fail in winter storms',
      'Heat pump installations — growing demand in Bath as homeowners move away from gas boilers',
      'Period property heating — Bath\'s Georgian and Victorian homes need heating engineers who understand older systems',
      'Annual boiler servicing — reliable, recurring work from Bath homeowners and landlords',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Do heating engineers in Bath need a website?', a: 'Yes. When a boiler breaks at midnight, homeowners search "emergency heating engineer Bath" on their phone. If you don\'t have a website, you don\'t appear — and they call someone who does.' },
      { q: 'Should my website show my Gas Safe badge?', a: 'Absolutely. Gas Safe registration is the first thing homeowners check. It should be visible on every page of your website, not buried on a subpage. We place it front and centre.' },
      { q: 'Can I target "boiler repair Bath" specifically?', a: 'Yes. Boiler repair is one of the most valuable local search terms for heating engineers. We build a dedicated boiler repair page optimised for Bath searches.' },
      { q: 'Do heat pump searches matter in Bath?', a: 'Increasingly yes. Government grants and environmental targets are driving heat pump installations. "Heat pump installer Bath" is a growing search term. A heat pump page future-proofs your website.' },
    ],
  },
  plasterers: {
    tradeName: 'Plasterers',
    tradeSlug: 'plasterers',
    metaTitle: 'Web Design for Plasterers in Bath | From £250 | SEO Kings',
    metaDescription: 'Websites for plasterers in Bath that rank on Google. Service pages, before/after gallery, area coverage. Local SEO for Bath plasterers from £250.',
    headline: 'Web Design for Plasterers in Bath',
    intro: 'Bath\'s period properties need specialist plastering — lime plaster, traditional cornicing, decorative ceiling roses, and artex removal from 20th-century homes. When someone searches "plasterer Bath", they want someone who understands Bath\'s building stock. We build plasterer websites that prove you do.',
    bathSpecifics: [
      'Lime plaster expertise — Bath\'s Georgian buildings need breathable lime plaster, not modern gypsum',
      'Decorative plasterwork — cornices, ceiling roses, ceiling medallions are features of Bath\'s period properties',
      'Artex removal — Bath\'s 1970s and 80s housing often needs artex ceiling removal and skim coating',
      'Rendering and external plasterwork — Bath stone properties need sympathetic exterior renders',
      'Dry lining and skim coating — modern Bath extensions and renovations need clean, flat plaster finishes',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Why do plasterers in Bath need a specialist website?', a: '"Plasterer Bath" is a regular search, but Bath homeowners specifically look for plasterers who understand period properties. Lime plaster, decorative work, and listed building requirements — your Bath page should mention these to win those jobs.' },
      { q: 'Should I show before and after photos?', a: 'Yes. Plastering transformations are more visual than people expect — rough Artex ceilings becoming perfect smooth finishes, damaged cornices restored. Before/after photos sell your work.' },
      { q: 'Do I need to mention lime plaster on my website?', a: 'Yes if you do it. Lime plaster is essential for Bath\'s listed buildings because gypsum traps moisture. Homeowners who know this specifically search for "lime plasterer Bath" — you should target that term.' },
      { q: 'Can you write Bath-specific plastering content?', a: 'Yes. We write copy that mentions Bath stone, lime plaster, cornice restoration, artex removal and conservation area considerations. It reads naturally because we understand the Bath building landscape.' },
    ],
  },
  'gas-engineers': {
    tradeName: 'Gas Engineers',
    tradeSlug: 'gas-engineers',
    metaTitle: 'Web Design for Gas Engineers in Bath | From £250 | SEO Kings',
    metaDescription: 'Websites for Gas Safe engineers in Bath that rank on Google. Gas Safe badge, emergency page, boiler pages. Local SEO for Bath gas engineers from £250.',
    headline: 'Web Design for Gas Engineers in Bath',
    intro: 'When a boiler breaks in Bath, homeowners reach for their phone. "Gas engineer Bath", "boiler repair Bath", "emergency gas safe plumber" — these are urgent, high-value searches. We build gas engineer websites that show your Gas Safe credentials front and centre, your emergency availability, and your local knowledge of Bath properties.',
    bathSpecifics: [
      'Gas Safe registration display — the first thing Bath homeowners check; must be visible on every page',
      'Emergency boiler repair — Bath period properties have older heating systems that fail in cold snaps',
      'Annual boiler servicing — recurring work from Bath landlords and homeowners',
      'Heat pump installations — growing demand as Bath homeowners move away from gas boilers',
      'Gas safety certificates — landlords in Bath need annual CP12 certificates, a reliable revenue stream',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Do gas engineers in Bath need a specialist website?', a: 'Yes. When a boiler fails at midnight, homeowners search "emergency gas engineer Bath" on their phone. If you do not have a website with your Gas Safe number and emergency phone number, you are invisible to those urgent searches.' },
      { q: 'Should my Gas Safe badge be on every page?', a: 'Absolutely. Gas Safe registration is the number one trust signal for gas engineers. Homeowners will not call a gas engineer who does not show their Gas Safe number. We make it prominent on every page.' },
      { q: 'Do I need a separate page for boiler repair and boiler installation?', a: 'Yes. They are different search intents. "Boiler repair Bath" is emergency; "new boiler Bath" is research. Separate pages capture both types of search and give customers the right information.' },
      { q: 'Can I target landlord gas safety certificates?', a: 'Yes. Bath has a large rental market. "Gas safety certificate Bath" or "CP12 Bath" are specific searches with lower competition. A dedicated page targeting landlords is easy to rank and brings recurring work.' },
    ],
  },
  'loft-conversions': {
    tradeName: 'Loft Conversion Specialists',
    tradeSlug: 'loft-conversions',
    metaTitle: 'Web Design for Loft Conversion Specialists in Bath | From £250 | SEO Kings',
    metaDescription: 'Websites for loft conversion specialists in Bath that rank on Google. Project galleries, planning pages, area coverage. Local SEO from £250.',
    headline: 'Web Design for Loft Conversion Specialists in Bath',
    intro: 'Loft conversions are one of the highest-value home improvements in Bath — £20-50k projects from homeowners who need more space without moving. "Loft conversion Bath", "dormer loft Keynsham" — these are considered, high-value searches. We build websites that showcase your projects and win these big contracts.',
    bathSpecifics: [
      'Bath conservation area restrictions — many Bath lofts need planning permission, unlike permitted development elsewhere',
      'Period property expertise — Bath Georgian and Victorian roofs need specialist structural knowledge',
      'Dormer and Velux conversions — the two main loft types in Bath, each needing dedicated pages',
      'Hip-to-gable conversions — common in Bath semi-detached properties',
      'Staircase design — Bath loft conversions often need creative staircase solutions for tight spaces',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Do loft conversion specialists need a specialist website?', a: 'Yes. Loft conversions are high-value decisions — £20-50k investments. Bath homeowners research carefully, looking at portfolios and planning expertise. A professional website with project galleries wins these contracts.' },
      { q: 'Should I mention Bath planning permission on my website?', a: 'Absolutely. Bath conservation areas mean many loft conversions need planning permission that would be permitted development elsewhere. Homeowners specifically search "loft conversion planning permission Bath" — your page should answer this.' },
      { q: 'How important are before and after photos?', a: 'Critical. Loft conversions are visual transformations — a dusty attic becoming a stunning bedroom or office. Before/after photos are the most persuasive content on your website and also rank in Google image search.' },
      { q: 'Can I target specific Bath neighbourhoods?', a: 'Yes. We build area pages for Bath postcodes and neighbourhoods. "Loft conversion Lansdown" or "dormer loft Widcombe" are low-competition searches that bring targeted enquiries.' },
    ],
  },
  'extension-builders': {
    tradeName: 'Extension Builders',
    tradeSlug: 'extension-builders',
    metaTitle: 'Web Design for Extension Builders in Bath | From £250 | SEO Kings',
    metaDescription: 'Websites for extension builders in Bath that rank on Google. Project galleries, planning pages, area coverage. Local SEO for Bath extension builders from £250.',
    headline: 'Web Design for Extension Builders in Bath',
    intro: 'Home extensions in Bath are big business — £30-80k projects from homeowners who cannot or will not move. "House extension Bath", "single storey extension Keynsham" — these are considered, high-value searches from people with budgets. We build extension builder websites that showcase your projects and convert these searches into contracts.',
    bathSpecifics: [
      'Bath conservation area planning — extensions in Bath often need planning permission that would be permitted development elsewhere',
      'Listed building consent — Bath has thousands of listed properties where extensions require specialist approval',
      'Bath stone extensions — matching existing Bath stone facades is a specialist skill homeowners specifically search for',
      'Wrap-around extensions — popular for Bath Victorian terraces to create open-plan living',
      'Kitchen-diner extensions — the most common extension type in Bath, combining kitchen fitting and building work',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Do extension builders in Bath need a specialist website?', a: 'Yes. Extensions are the highest-value home improvement — £30-80k projects. Bath homeowners research builders carefully, looking at portfolios, planning expertise and reviews. A professional website with project galleries is essential to win these contracts.' },
      { q: 'Should I mention Bath planning permission?', a: 'Absolutely. Bath conservation areas and listed buildings mean planning is more complex than most areas. A planning permission page shows you understand Bath planning and captures "extension planning permission Bath" searches.' },
      { q: 'Do I need separate pages for different extension types?', a: 'Yes. "Single storey extension Bath" and "double storey extension Bath" are different searches. Dedicated pages let you target both and give homeowners the specific information they want.' },
      { q: 'Can I target Bath stone and heritage extensions?', a: 'Yes. Bath stone matching and heritage extension work are specialist searches with low competition in Bath. Dedicated pages position you as the expert and win these high-value enquiries.' },
    ],
  },
  'drainage-engineers': {
    tradeName: 'Drainage Engineers',
    tradeSlug: 'drainage-engineers',
    metaTitle: 'Web Design for Drainage Engineers in Bath | From £250 | SEO Kings',
    metaDescription: 'Websites for drainage engineers in Bath that rank on Google.emergency page, CCTV survey pages, area coverage. Local SEO for Bath drainage engineers from £250.',
    headline: 'Web Design for Drainage Engineers in Bath',
    intro: 'Drainage problems are urgent and expensive. When a Bath homeowner searches "drain unblocking Bath" or "CCTV drain survey Bath", they need help now — and they call the first number they see. We build drainage engineer websites that show your 24/7 availability, your specialist equipment and your local knowledge of Bath drains.',
    bathSpecifics: [
      'Bath aging drainage — Bath has Victorian drainage infrastructure that regularly causes blockages and subsidence',
      'Emergency drain unblocking — the highest-value search for drainage engineers in Bath, especially in winter',
      'CCTV drain surveys — Bath homeowners and buyers regularly need drain surveys for property purchases',
      'Drain repairs and relining — Bath clay-pipe drainage systems often need lining or replacement',
      'Surface water drainage — Bath hillside properties need soakaway and surface water solutions',
    ],
    bathAreas: [
      'Bath city centre (BA1)',
      'Widcombe & Bathwick',
      'Larkhall & Fairfield Park',
      'Newbridge & Weston',
      'Lansdown & Upper Lansdown',
      'Combe Down & Odd Down',
    ],
    faqs: [
      { q: 'Do drainage engineers in Bath need a specialist website?', a: 'Yes. When drains block, homeowners search "drain unblocking Bath" on their phone. If you do not have a website with a clickable emergency phone number, you are invisible. The first result gets the call.' },
      { q: 'Should I include an emergency page?', a: 'Essential. Drainage problems are urgent. A dedicated emergency page with your 24/7 phone number visible at the top captures "drain unblocking near me" searches when people are desperate and calling the first number they find.' },
      { q: 'Does a CCTV drain survey page help with SEO?', a: 'Yes. "CCTV drain survey Bath" is a specific, lower-competition search. Home buyers and solicitors search for it during conveyancing. A dedicated page captures this recurring, high-value work.' },
      { q: 'Can I target Bath-specific drainage issues?', a: 'Yes. Bath Victorian drains, clay pipe problems and hillside drainage are Bath-specific issues. Mentioning them on your website shows local expertise and targets long-tail searches with less competition.' },
    ],
  },
};